import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";

const SairaFont = Saira({
  weight: "variable",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${SairaFont.className} antialiased`}>{children}</body>
    </html>
  );
}
